--Create procedure
--CALL RETRIEVE_ALL;      -- Caller query
--DROP PROCEDURE RETRIEVE_ALL;
--CALL RETRIEVE_ALL;


--Update sale price
--CALL RETRIEVE_ALL;
--CALL UPDATE_SALEPRICE(1, 'BAD');        -- Caller query
--CALL RETRIEVE_ALL;

--CALL RETRIEVE_ALL;
--CALL UPDATE_SALEPRICE(3, 'WORSE');      -- Caller query
--CALL RETRIEVE_ALL;

DROP PROCEDURE UPDATE_SALEPRICE;
CALL UPDATE_SALEPRICE(3, 'WORSE');